[package]
name = "el-gamal-encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
rand = "0.8"
aes = "0.7"
block-modes = "0.8"
